services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
      - "443:443"   # WebSocket connections
    command:
      - "--config=/etc/nats/nats-server.conf"
    environment:
      - JWT_SECRET=test-secret
    volumes:
      - nats-data:/data
      - ./run/nats-server.conf:/etc/nats/nats-server.conf:ro
    restart: unless-stopped

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  nats-data:
  postgres-data: