syntax = "proto3";

package mythicisland.queue.v1;

import "queue_types.proto";

option java_package = "net.mythicisland.queue.v1";
option java_multiple_files = true;

message EnqueueRequest {
  string type = 1;
  repeated string player_ids = 2;
}

message EnqueueResponse {
  Queue queue = 1;
}

message DequeueRequest {
  repeated string player_ids = 1;
}

message DequeueResponse {
  Queue queue = 1;
}


service QueueService {
  rpc Enqueue(EnqueueRequest) returns (EnqueueResponse);
  rpc Dequeue(DequeueRequest) returns (DequeueResponse);
}