syntax = "proto3";

package mythicisland.queue.v1;

option java_package = "net.mythicisland.queue.v1";
option java_multiple_files = true;

message Queue {
  string unique_id = 1;
  string type = 2;
  QueueStatus status = 3;
  repeated string player_ids = 5;
}

message QueueType {
  string name = 1;
  string group = 2;
  uint32 min_capacity = 3;
  uint32 max_capacity = 4;
  optional int64 waiting_countdown_millis = 5;
  optional int64 countdown_millis = 6;
}

message QueueStats {
  string queue_type = 1;
  QueueRating rating = 2;
  uint32 total_players_7d = 3;   // Total players in the last 7 days
  uint32 total_players_24h = 4;  // Total players in the last 24 hours
  double share_percent = 5;      // Relative share compared to all queue types
  double trend_percent = 6;      // 24h vs. 7-day average in %
}

enum QueueStatus {
  NOT_ENOUGH_PLAYERS = 0;
  WAITING_COUNTDOWN = 1;
  SEARCHING_SERVER = 2;
  WAITING_FOR_SERVER = 3;
  SERVER_READY = 4;
  COUNTDOWN = 5;
  TELEPORTING = 6;
  FINISHED = 7;
}

enum QueueRating {
  DEAD = 0;
  LOW = 1;
  GOOD = 2;
  POPULAR = 3;
}