syntax = "proto3";

package mythicisland.queue.v1;

import "queue_types.proto";

option java_package = "net.mythicisland.queue.v1";
option java_multiple_files = true;

message EnqueueRequest {
  string type = 1;
  repeated string player_ids = 2;
}

message EnqueueResponse {
  Queue queue = 1;
}

message DequeueRequest {
  repeated string player_ids = 1;
}

message DequeueResponse {
  Queue queue = 1;
}

service QueueService {
  rpc Enqueue(EnqueueRequest) returns (EnqueueResponse);
  rpc Dequeue(DequeueRequest) returns (DequeueResponse);
}

message GetQueueRequest {
  string queue_id = 1;
}

message GetQueueResponse {
  Queue queue = 1;
}

message GetAllQueuesRequest {}

message GetAllQueuesResponse {
  repeated Queue queues = 1;
}

message GetQueuesByTypeRequest {
  string type = 1;
}

message GetQueuesByTypeResponse {
  repeated Queue queues = 1;
}

message GetQueueByPlayerRequest {
  string player_id = 1;
}

message GetQueueByPlayerResponse {
  Queue queue = 1;
}

message GetPlayerPositionRequest {
  string player_id = 1;
}

message GetPlayerPositionResponse {
  Queue queue = 1;
  uint32 position = 2;
}

message GetQueueTypeRequest {
  string name = 1;
}

message GetQueueTypeResponse {
  QueueType queue_type = 1;
}

message GetAllQueueTypesRequest {}

message GetAllQueueTypesResponse {
  repeated QueueType queue_types = 1;
}

service QueueDataService {
  rpc GetQueue(GetQueueRequest) returns (GetQueueResponse);
  rpc GetAllQueues(GetAllQueuesRequest) returns (GetAllQueuesResponse);
  rpc GetQueuesByType(GetQueuesByTypeRequest) returns (GetQueuesByTypeResponse);
  rpc GetQueueByPlayer(GetQueueByPlayerRequest) returns (GetQueueByPlayerResponse);
  rpc GetPlayerPosition(GetPlayerPositionRequest) returns (GetPlayerPositionResponse);
  rpc GetQueueType(GetQueueTypeRequest) returns (GetQueueTypeResponse);
  rpc GetAllQueueTypes(GetAllQueueTypesRequest) returns (GetAllQueueTypesResponse);
}
