name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Publish with Gradle
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
        run: chmod +x ./gradlew && ./gradlew :queue-api:publish